export const GET_DESTINY_USER_PROFILE_REQUEST = "GET_DESTINY_USER_PROFILE_REQUEST";
export const GET_DESTINY_USER_PROFILE_SUCCESS = "GET_DESTINY_USER_PROFILE_SUCCESS";
export const GET_DESTINY_USER_PROFILE_FAILURE = "GET_DESTINY_USER_PROFILE_FAILURE";